src/elombard/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.utils import translation
from django.views import generic
from django.views.static import serve

# from content.views import dashboard
from home.views import *
from django.views import static
from django.conf import settings
# from general import set_lang as core_views


urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^admin/', admin.site.urls,name="admin"),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT }, name='media'),
]

translation.activate(settings.LANGUAGE_CODE)

# urlpatterns += i18n_patterns(
urlpatterns += [

    # url(r'^', include("home.urls", namespace="home")),
    url(r'^', include("panel.urls", namespace="panel")),
    # url(r'^', include("content.urls", namespace="content")),

    url(r'^auth/', include("base_user.urls", namespace="base-user")),

]

urlpatterns += staticfiles_urlpatterns()




@login_required
def protected_serve(request, path, document_root=None, show_indexes=False):
    return serve(request, path, document_root, show_indexes)


if settings.DEBUG is False:   #if DEBUG is True it will be served automatically
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT }, name='static'),
        url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT }, name='media')
    ]
urlpatterns += staticfiles_urlpatterns()

src/panel/urls.py
from django.conf.urls import url

from .views import *


urlpatterns = [
	url(r'^$', dashboard, name='dashboard'),
	# url(r'^video-posts/list/$', video_posts, name='video-posts'),
	# url(r'^customers/list/$', customer_list, name='customer-list'),
	url(r'^customers/list/(?P<type>[\w-]+)/$', customer_list_type, name='customer-list-type'),
	url(r'^customers/list/m/ajax/$', customer_list_ajax, name='customer-ajax-list'),
	url(r'^customers/create/$', add_customer, name='customer-create'),
	url(r'^customers/edit/(?P<id>[0-9]+)/$', edit_customer, name='customer-edit'),

	url(r'^packages/annuitet/(?P<id>[0-9]+)/$', package_annuitet, name='package-annuitet'),
	url(r'^packages-an/annuitet-general/$', general_annuitet, name='general-annuitet'),
	url(r'^packages-an/upload_base64/$', upload_base64, name='upload_base64'),


	url(r'^statistic/(?P<type>[\w-]+)/$', statistic_type, name='statistic-type'),




	url(r'^packages/list/$', package_list, name='package-list'),
	url(r'^packages/list/(?P<type>[\w-]+)/$', package_list_type, name='package-list-type'),
	url(r'^packages/list/infinity/(?P<type>[\w-]+)/$', package_list_type_infinity, name='package-list-type-infinity'),
	url(r'^packages/package-daily-note-write/(?P<id>[0-9]+)/$', package_daily_note_ajax, name='package-daily-note'),
	url(r'^packages/package-daily-note-list/(?P<id>[0-9]+)/$', package_daily_note_list, name='package-daily-list'),
	url(r'^product-type/get-ajax/$', product_type_ajax, name='product-type-ajax'),
	url(r'^packages/closed-reason/(?P<id>[0-9]+)/$', package_closed_reason, name='package-closed-reason'),
	url(r'^packages/waiting/list/(?P<type>[\w-]+)/$', package_waiting_list, name='package-waiting-list'),
	url(r'^packages/waiting/edit/(?P<id>[0-9]+)/$', package_waiting_edit, name='package-waiting-edit'),
	url(r'^packages/waiting/list/(?P<p_id>[0-9]+)/(?P<type>[\w-]+)/$', package_waiting_list_package, name='package-waiting-list-package'),

	url(r'^packages/create/$', package_create, name='package-create'),
	url(r'^packages/edit/(?P<id>[0-9]+)/$', package_edit, name='package-edit'),
	url(r'^package-atachment-upload/(?P<id>[0-9]+)/ajax/$', package_atachment_upload, name='package-atachment-upload'),



	url(r'^packages/payments-edit/(?P<id>[0-9]+)/$', package_payment_edit, name='package-payments-edit'),
	url(r'^packages/payments-refresh/(?P<id>[0-9]+)/$', package_payment_refresh, name='package-payments-refresh'),
	url(r'^packages/payments-remove/(?P<id>[0-9]+)/$', package_payment_remove, name='package-payments-remove'),
	url(r'^packages/payments-new-generate/(?P<id>[0-9]+)/$', package_payment_new_generate, name='package-payments-new-generate'),
	url(r'^packages/payment-new-check/(?P<id>[0-9]+)/$', package_payment_new_check, name='package-payment-new-check'),
	url(r'^packages/payment-new-add/(?P<id>[0-9]+)/$', package_payment_new_add, name='package-payment-new-add'),
	url(r'^packages/payment-ajax/(?P<id>[0-9]+)/$', package_payment_add, name='package-add-paymanet'),

	url(r'^packages/ordered/list/$', package_ordered_list, name='package-ordered-list'),
	url(r'^packages/next/(?P<o_slug>[\w-]+)/(?P<id>[0-9]+)/$', package_next, name='package-next'),
	url(r'^packages/ordered/edit/(?P<id>[0-9]+)/$', package_ordered_edit, name='package-ordered-edit'),

    url(r'^salaries/list/$', salary_list, name='salary-list'),
	url(r'^employees/list/$', employee_list, name='employee-list'),
	url(r'^employees/create/$', employee_create, name='employee-create'),
	url(r'^employees/edit/(?P<id>[0-9]+)/$', employee_edit, name='employee-edit'),

	url(r'^employees-permit/list/$', employee_permit_list, name='employee-permit-list'),
	url(r'^employees-permit/create/$', employee_permit_create, name='employee-permit-create'),
	url(r'^employees-permit/edit/(?P<id>[0-9]+)/$', employee_permit_edit, name='employee-permit-edit'),

	url(r'^reports/logs/list/$', log_list, name='log-list'),
	url(r'^reports/logs/outcome/ajax/$', logo_outcome_data_ajax, name='logo-outcome-ajax-data-list'),
	url(r'^reports/logs/detail/(?P<id>[0-9]+)/$', log_detail, name='log-detail'),
	url(r'^reports/(?P<o_slug>[\w-]+)/list/$', income_outcome_list, name='income-outcome-list'),
	url(r'^reports/list/kassa/$', income_outcome_case, name='income-outcome-case'),
	url(r'^reports/list/kassa/$', income_outcome_case, name='income-outcome-case'),
	url(r'^reports/(?P<o_slug>[\w-]+)/create/$', income_outcome_create, name='income-outcome-create'),
	url(r'^reports/(?P<o_slug>[\w-]+)/edit/(?P<id>[0-9]+)/$', income_outcome_edit, name='income-outcome-edit'),


	url(r'^currency/list/$', currency_list, name='currency-list'),
	url(r'^currency/create/$', currency_create, name='currency-create'),
	url(r'^currency/edit/(?P<id>[0-9]+)/$', currency_edit, name='currency-edit'),

	url(r'^customer-notes/list/(?P<c_id>[0-9]+)/$', customer_notes_list, name='customer-notes-list'),
	url(r'^customer-notes/create/(?P<c_id>[0-9]+)/$', customer_notes_create, name='customer-notes-create'),
	url(r'^customer-notes/edit/(?P<c_id>[0-9]+)/(?P<id>[0-9]+)/$', customer_notes_edit, name='customer-notes-edit'),

	url(r'^departments/list/', department_list, name='department-list'),
	url(r'^departments/create/', department_create, name='department-create'),
	url(r'^departments/edit/(?P<id>[0-9]+)/', department_edit, name='department-edit'),

	url(r'^package-types/list/', package_type_list, name='package_type-list'),
	url(r'^package-types/create/', package_type_create, name='package_type-create'),
	url(r'^package-types/edit/(?P<id>[0-9]+)/', package_type_edit, name='package_type-edit'),
	url(r'^package-types/remove/(?P<id>[0-9]+)/', package_type_remove, name='package_type-remove'),

	url(r'^product/list/', product_list, name='product-list'),
	url(r'^product/create/', product_create, name='product-create'),
	url(r'^product/edit/(?P<id>[0-9]+)/', product_edit, name='product-edit'),
	url(r'^product/remove/(?P<id>[0-9]+)/', product_remove, name='product-remove'),

	url(r'^product-type/generate/', product_generate, name='product-type-generate-ajax'),
	url(r'^product-type/list/(?P<p_id>[0-9]+)/', product_type_list, name='product-type-list'),
	url(r'^product-type/create/(?P<p_id>[0-9]+)/', product_type_create, name='product-type-create'),
	url(r'^product-type/edit/(?P<p_id>[0-9]+)/(?P<id>[0-9]+)/', product_type_edit, name='product-type-edit'),
	url(r'^product-type/remove/(?P<p_id>[0-9]+)/(?P<id>[0-9]+)/', product_type_remove, name='product-type-remove'),

	url(r'^package-product/remove/(?P<id>[0-9]+)/', package_product_remove, name='package-product-image-remove'),


 ]

src/templates/panel/customers/notes/detail.html
{% extends 'panel-base.html' %}
{% load static %}{% load i18n %}
{% block title_block %}
{% trans 'Qeyd' %}
{% endblock %}
{% block css_block %}

{% endblock %}
{% block content_block %}

    <!-- begin app-main -->
    <div class="app-main" id="main">
        <!-- begin container-fluid -->
        <div class="container-fluid">
            <!-- begin row -->
            <div class="row">
                <div class="col-md-12 m-b-30">
                    <!-- begin page title -->
                    <div class="d-block d-sm-flex flex-nowrap align-items-center">
                        <div class="page-title mb-2 mb-sm-0">
                            <h1>Bildiriş mətni</h1>
                        </div>
                        <div class="ml-auto d-flex align-items-center">
                            <nav>
                                <ol class="breadcrumb p-0 m-b-0">

                                    <li class="breadcrumb-item">
                                        <a href="{% url 'panel:dashboard' %}"><i class="ti ti-home"></i></a>
                                    </li>

                                    <li class="breadcrumb-item">
                                        <a href="{% url 'panel:notification-list' %}">Qeydlər</a>
                                    </li>
                                    <li class="breadcrumb-item active text-primary">
                                        {% trans "Qeyd" %} {{ data_obj.id }}
                                    </li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                    <!-- end page title -->
                </div>
            </div>
            <!-- end row -->

            <!--mail-Compose-contant-start-->
            <div class="row account-contant">
                <div class="col-12">
                    <div class="card card-statistics">
                        <div class="card-body p-0">
                            <div class="row no-gutters">
                                <div class="col-xl-4 col-md-4 pb-xl-0 pb-5 border-right">
                                    <div class="page-account-profil">
                                        <div class="profile-img text-center rounded-circle">
                                            <div class="pt-5 pb-5">
                                                <div class="bg-img m-auto">
                                                    <img src="{% static 'main/assets/img/no-avatar-50.jpg' %}" class="img-fluid" alt="users-avatar">
                                                </div>
                                                <div class="profile pt-4">
                                                    <h4 class="mb-1">{{ data_obj.title }}</h4>
                                                    <p>{{ data_obj.date }}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-8 col-md-8 col-12 border-t border-right">
                                    <div class="page-account-form">
                                        <div class="form-titel border-bottom p-3">
                                            <h5 class="mb-0 py-2">Qeyd mətni</h5>
                                        </div>
                                        <div class="p-4">
                                            {% autoescape off %}
                                                {{ data_obj.content }}
                                            {% endautoescape %}

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--mail-Compose-contant-end-->
        </div>
        <!-- end container-fluid -->
    </div>
    <!-- end app-main -->

{% endblock %}
{% block js_block %}
    <script>
        activeMenu('customers');
    </script>



{% endblock %}

src/templates/panel/customers/notes/form.html
{% extends 'panel-base.html' %}
{% load static %}{% load i18n %}
{% block title_block %}

{% endblock %}
{% block css_block %}

{% endblock %}
{% block content_block %}
    <!-- begin app-main -->
    <div class="app-main" id="main">
        <!-- begin container-fluid -->
        <div class="container-fluid">
            <!-- begin row -->
            <div class="row">
                <div class="col-md-12 m-b-30">
                    <!-- begin page title -->
                    <div class="d-block d-sm-flex flex-nowrap align-items-center">
                        <div class="page-title mb-2 mb-sm-0">
                            <h1>
                                {% trans "Qeyd" %} {% if data_obj %} - {{ data_obj.title }}{% else %} {% trans 'yaz' %} {% endif %}
                            </h1>
                        </div>
                        <div class="ml-auto d-flex align-items-center">
                            <nav>
                                <ol class="breadcrumb p-0 m-b-0">
                                    <li class="breadcrumb-item">
                                        <a href="{% url 'panel:dashboard' %}"><i class="ti ti-home"></i></a>
                                    </li>
                                    <li class="breadcrumb-item">
                                        <a href="{% url 'panel:customer-list' %}">{% trans 'Müştərilər' %}</a>
                                    </li>
                                    <li class="breadcrumb-item">
                                        <a href="{% url 'panel:customer-notes-list' customer_obj.id %}">{% trans 'Qeydlər' %}</a>
                                    </li>
                                    <li class="breadcrumb-item active text-primary">
                                        {% trans "Qeyd" %} {% if data_obj %} - {{ data_obj.title }}{% else %} {% trans 'Əlavə et' %} {% endif %}
                                    </li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                    <!-- end page title -->
                </div>
            </div>
            <!-- end row -->
            <!-- begin row -->
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-statistics">
                        <div class="card-header">
                            <div class="card-heading">
                                <h4 class="card-title">
                                    {% trans "Qeyd" %} {% if data_obj %} - {{ data_obj.title }}{% else %} {% trans 'yaz' %} {% endif %}
                                </h4>
                            </div>
                        </div>
                        <form class="card-body" method="post" action="">
                            {% csrf_token %}
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon1">{{ form.title.label }}</span>
                                </div>
                                {{ form.title }}
                            </div>
                            {% if form.title.errors %}
                                <div class="alert alert-danger mb-3" role="alert">
                                    {{ form.title.errors }}
                                </div>
                            {% endif %}
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon1">{{ form.description.label }}</span>
                                </div>
                                {{ form.description }}
                            </div>
                            {% if form.description.errors %}
                                <div class="alert alert-danger mb-3" role="alert">
                                    {{ form.description.errors }}
                                </div>
                            {% endif %}
                            <button type="submit" class="btn btn-block btn-success">
                                {% if data_obj %} {% trans 'Dəyiş' %} {% else %} {% trans 'Əlavə et' %} {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
            <!-- end row -->
        </div>
        <!-- end container-fluid -->
    </div>
    <!-- end app-main -->
{% endblock %}
{% block js_block %}
    <script>
        activeMenu('customers');
    </script>


<script>
    {% if success_message %}
        swal({
            type: 'success',
            title: '{% trans 'Success' %}',
            text: '{{ success_message }}'
        });
    {% endif %}
</script>

{% endblock %}

src/templates/panel/customers/notes/list.html
{% extends 'panel-base.html' %}
{% load static %}{% load i18n %}
{% block title_block %}
{% trans 'Muştəri qeydləri' %}
{% endblock %}
{% block css_block %}
    <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />
    <link href="https://cdn.datatables.net/buttons/1.5.6/css/buttons.bootstrap4.min.css" rel="stylesheet" type="text/css" />
    <link href="https://cdn.datatables.net/buttons/1.5.6/css/buttons.bootstrap4.min.css" rel="stylesheet" type="text/css" />
    <style>
    .dt-buttons .dt-button{
        padding:.5rem 1.6rem!important;
        border-radius: 5px;
        border:none;
        cursor: pointer;
        background: #8d8d8d;
        color:#fff!important
    }
    .dt-buttons .dt-button:hover{
        border:none;
        background: #3a3d44;
        color:#fff!important
    }

    </style>
{% endblock %}
{% block content_block %}
    <!-- begin app-main -->
    <div class="app-main" id="main">
        <!-- begin container-fluid -->
        <div class="container-fluid">
            <!-- begin row -->
            <div class="row">
                <div class="col-md-12 m-b-30">
                    <!-- begin page title -->
                    <div class="d-block d-sm-flex flex-nowrap align-items-center">
                        <div class="page-title mb-2 mb-sm-0">
                            <h1>
                                {% trans "Muştəri qeydləri" %}
                            </h1>
                        </div>
                        <div class="ml-auto d-flex align-items-center">
                            <nav>
                                <ol class="breadcrumb p-0 m-b-0">
                                    <li class="breadcrumb-item">
                                        <a href="{% url 'panel:dashboard' %}"><i class="ti ti-home"></i></a>
                                    </li>
                                    <li class="breadcrumb-item">
                                        <a href="{% url 'panel:customer-list' %}">{% trans 'Müştərilər' %}</a>
                                    </li>
                                    <li class="breadcrumb-item active text-primary">
                                        {% trans "Muştəri qeydləri" %}
                                    </li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                    <!-- end page title -->
                </div>
            </div>
            <!-- end row -->
            <!-- begin row -->
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-statistics">
                        <div class="card-header">
                            <div class="card-heading">
                                <h4 class="card-title">
                                    {% trans "Muştəri qeydləri" %}

                                </h4>
                                <hr/>
                                <a class="btn btn-success" href="{% url 'panel:customer-notes-create' customer_obj.id %}"> {% trans 'Qeyd yaz' %}</a>
                            </div>
                        </div>
                        <div class="card-body">
                            <table id="example" class="table table-striped table-bordered" style="width:100%">
                                <thead>
                                    <tr>
                                        <th>N</th>
                                        <th>{% trans 'Başlıq' %}</th>
                                        <th>{% trans 'Tarix' %}</th>
                                        <th>/</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for data_item in data_list %}
                                        <tr>
                                            <td>{{ forloop.counter }}</td>
                                            <td>{{ data_item.title }}</td>
                                            <td>{{ data_item.date }}</td>
                                            <td>
                                                <a href="{% url 'panel:customer-notes-edit' customer_obj.id data_item.id %}" class="btn btn-icon btn-square btn-warning">
                                                    <i class="fa fa-edit"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    {% endfor %}

                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>N</th>
                                        <th>{% trans 'Başlıq' %}</th>
                                        <th>{% trans 'Tarix' %}</th>
                                        <th>/</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end row -->
        </div>
        <!-- end container-fluid -->
    </div>
    <!-- end app-main -->
{% endblock %}
{% block js_block %}
    <script>
        activeMenu('customers');
    </script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.print.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.colVis.min.js "></script>
    <script>
    $(document).ready(function() {
    var table = $('#example').DataTable( {
        lengthChange: true,
        buttons: [ 'copy', 'excel', 'pdf' ]
    } );

    table.buttons().container()
        .appendTo( '#example_wrapper .col-md-6:eq(0)' );
} );
    </script>
{% endblock %}